In [2]:
import pandas as pd
import world_trade_data as wits

In [4]:
wits.get_countries()

,name,notes,countrycode,isreporter,ispartner,isgroup,grouptype
iso3Code,,,,,,,
AFG,Afghanistan,,004,False,False,No,N/A
ALB,Albania,,008,False,False,No,N/A
DZA,Algeria,,012,False,False,No,N/A
ASM,American Samoa,,016,True,False,No,N/A
AND,Andorra,,020,False,False,No,N/A
...,...,...,...,...,...,...,...
YEM,Yemen,,887,False,False,No,N/A
YDR,Yemen Democratic,,720,True,False,No,N/A
YUG,"Yugoslavia,FR(Serbia/Montenegr",,890,True,False,No,N/A
ZMB,Zambia,,894,False,False,No,N/A
ZWE,Zimbabwe,,716,False,False,No,N/A

In [5]:
wits.get_products()

,isgroup,nomenclaturecode,grouptype,productdescription,notes
productcode,,,,,
999999,N/A,N/A,N/A,Not Applicable,
01-05_Animal,Yes,H0,Sector,Animal,
06-15_Vegetable,Yes,H0,Sector,Vegetable,
16-24_FoodProd,Yes,H0,Sector,Food Products,
25-26_Minerals,Yes,H0,Sector,Minerals,
27-27_Fuels,Yes,H0,Sector,Fuels,
28-38_Chemicals,Yes,H0,Sector,Chemicals,
39-40_PlastiRub,Yes,H0,Sector,Plastic or Rubber,
41-43_HidesSkin,Yes,H0,Sector,Hides and Skins,
44-49_Wood,Yes,H0,Sector,Wood,
50-63_TextCloth,Yes,H0,Sector,Textiles and Clothing,
64-67_Footwear,Yes,H0,Sector,Footwear,
68-71_StoneGlas,Yes,H0,Sector,Stone and Glass,
72-83_Metals,Yes,H0,Sector,Metals,
84-85_MachElec,Yes,H0,Sector,Mach and Elec,
86-89_Transport,Yes,H0,Sector,Transportation,
90-99_Miscellan,Yes,H0,Sector,Miscellaneous,
Total,Yes,H0,Sector,All Products,
AgrRaw,Yes,S2,SITC-Rev2-Groups,Agricultural Raw Materials,
Chemical,Yes,S2,SITC-Rev2-Groups,Chemical,
Food,Yes,S2,SITC-Rev2-Groups,Food,
Fuels,Yes,S2,SITC-Rev2-Groups,Fuel,
manuf,Yes,S2,SITC-Rev2-Groups,Manufactures,
OresMtls,Yes,S2,SITC-Rev2-Groups,Ores and Metals,
Textiles,Yes,S2,SITC-Rev2-Groups,Textiles,
Transp,Yes,S2,SITC-Rev2-Groups,Machinery and Transport Equipment,
Total,Yes,H0,Stages-Of-Processing,All Products,
UNCTAD-SoP1,Yes,H0,Stages-Of-Processing,Raw materials,
UNCTAD-SoP2,Yes,H0,Stages-Of-Processing,Intermediate goods,
UNCTAD-SoP3,Yes,H0,Stages-Of-Processing,Consumer goods,
UNCTAD-SoP4,Yes,H0,Stages-Of-Processing,Capital goods,

In [7]:
wits.get_indicators()

,ispartnerequired,SDMX_partnervalue,isproductrequired,SDMX_productvalue,name,definition,source,topic,productclassification,periodicity,valuation,currency,notes
indicatorcode,,,,,,,,,,,,,
CNTRY-GRWTH,yes,,yes,,Country Growth (%),Annual percentage growth rate of the countryâ€™s...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,Export - FOB; Import - CIF,None,1) Mirror Exports is considered 2)Growth for a...
HH-MKT-CNCNTRTN-NDX,no,999,no,999999,HH Market concentration index,Hirschman Herfindahl index is a measure of th...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,Export - FOB; Import - CIF,None,1) Mirror Exports is considered for export dat...
MPRT-PRDCT-SHR,yes,,yes,,Product Share (%),The share of total merchandise trade (export o...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,
MPRT-PRTNR-SHR,yes,,no,999999,Partner Share (%),The share of total merchandise trade (export o...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,
MPRT-SHR-TTL-PRDCT,yes,,yes,,Share in Total Products (%),Share in Total Products (%),WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,1) All traded products at HS 6 digits are con...
MPRT-TRD-VL,yes,,yes,,Trade Value (US$ Thousand),Total Import/Export Value in thousands of US D...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,Export - FOB; Import - CIF,US Dollar - Current value,
NDX-XPRT-MKT-PNRTTN,no,999,no,999999,Index Of Export Market Penetration,It is calculated as the number of countries to...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,Export - FOB; Import - CIF,None,1) Mirror Exports is considered for export dat...
NMBR-MPRT-HS6-PRDCT,yes,,no,999999,No Of traded HS6 digit Products,Total number of products imported by a country...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,1) All traded products at HS 6 digits are con...
NMBR-MPRT-PRTNR,no,999,no,999999,Number of import partners,Number of countries from which a particular co...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,1) Product 'Total' is used for this computation.
NMBR-PRDCT-MPRTD,no,999,no,999999,Number of products imported,Total number of products imported by a country...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,1) All traded products at HS 6 digits are con...
NMBR-PRDCT-XPRTD,no,999,no,999999,Number of products exported,Total number of products exported by a country...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,1) All traded products at HS 6 digits are con...
NMBR-XPRT-HS6-PRDCT,yes,,no,999999,No Of traded HS6 digit Products,Total number of products exported by a country...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,1) All traded products at HS 6 digits are con...
NMBR-XPRT-PRTNR,no,999,no,999999,Number of export partners,Number of countries to whom a particular count...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,1) Product 'Total' is used for this computation.
RCA,yes,,yes,,Revealed comparative advantage,Measures of revealed comparative advantage (RC...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,Export - FOB; Import - CIF,None,Mirror Exports is considered. The RCA index o...
TRD-CMPLMNTRTY-NDX,yes,,no,999999,Trade complementarity index,The trade complementarity (TC) index can provi...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,Export - FOB; Import - CIF,None,1) Mirror Exports is considered for export dat...
WRLD-GRWTH,yes,,yes,,World Growth (%),Annual percentage growth rate of the worldâ€™s t...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,Export - FOB; Import - CIF,None,1) Mirror Exports is considered 2)Growth for a...
XPRT-PRDCT-SHR,yes,,yes,,Product Share (%),The share of total merchandise trade (export o...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,
XPRT-PRTNR-SHR,yes,,no,999999,Partner Share (%),The share of total merchandise trade (export o...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,
XPRT-SHR-TTL-PRDCT,yes,,yes,,Share in Total Products (%),Share in Total Products (%),WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,None,None,1) All traded products at HS 6 digits are con...
XPRT-TRD-VL,yes,,yes,,Trade Value (US$ Thousand),Total Import/Export Value in thousands of US D...,WITS - UNSD Comtrade,Trade,"Harmonized System 1988/92, SITC Revision 2",Annual,Export - FOB; Import - CIF,US Dollar - Current value,

In [44]:
import requests
url='https://comtrade.un.org/api/get?max=100&type=C&freq=A&px=HS&ps=2019&r=all&p=World&rg=all&cc=1206'
un_data=requests.get(url)
print(un_data.content)

b'{"validation":{"status":{"name":"Invalid parameter","value":5004,"category":0,"description":"the selected query does not accept the passed option.","helpUrl":"For more reference visit http://comtrade.un.org/data/dev/portal/"},"message":"Invalid argument format: \'World\', integers and keywords \'ALL\' only acceptable values","count":{"value":0,"started":"0001-01-01T00:00:00","finished":"0001-01-01T00:00:00","durationSeconds":0.0},"datasetTimer":null},"dataset":[]}'

### [API portal](https://comtrade.un.org/data/dev/portal#subscription)

In [31]:
print(un_data.status_code)

200

In [32]:
un_data.json()

{'validation': {'status': {'name': 'Invalid parameter',
   'value': 5004,
   'category': 0,
   'description': 'the selected query does not accept the passed option.',
   'helpUrl': 'For more reference visit http://comtrade.un.org/data/dev/portal/'},
  'message': "Invalid argument format: 'World', integers and keywords 'ALL' only acceptable values",
  'count': {'value': 0,
   'started': '0001-01-01T00:00:00',
   'finished': '0001-01-01T00:00:00',
   'durationSeconds': 0.0},
  'datasetTimer': None},
 'dataset': []}

In [35]:
read_file = pd.read_excel (r'.\data\raw\UN Comtrade Country List.xls')
read_file.to_csv(r'.\data\raw\UN Comtrade Country List.csv', index = None, header=True)

In [37]:
read_file

,ctyCode,cty Name English,cty Fullname English,Cty Abbreviation,Cty Comments,ISO2-digit Alpha,ISO3-digit Alpha,Start Valid Year,End Valid Year
0,0,World,World,World,NaN,WL,WLD,1962,2061
1,4,Afghanistan,Afghanistan,Afghanistan,NaN,AF,AFG,1962,2061
2,8,Albania,Albania,Albania,NaN,AL,ALB,1962,2061
3,10,Antarctica,Antarctica,Antarctica,NaN,NaN,ATA,1962,2061
4,12,Algeria,Algeria,Algeria,NaN,DZ,DZA,1962,2061
...,...,...,...,...,...,...,...,...,...
288,887,Yemen,Yemen,Yemen,NaN,YE,YEM,1991,2061
289,890,Fmr Yugoslavia,Former Yugoslavia,Fmr Yugoslavia,In 1992 including TFYR of Macedonia,YU,YUG,1962,1991
290,891,Serbia and Montenegro,Serbia and Montenegro,Serbia and Montenegro,NaN,CS,SCG,1992,2005
291,894,Zambia,Zambia,Zambia,NaN,ZM,ZMB,1965,2061
292,899,"Areas, nes","Areas, not elsewhere specified","Areas, nes",NaN,NaN,NaN,1962,2061

In [41]:
country_list = pd.read_csv(r'.\data\raw\UN Comtrade Country List.csv')
country_list

,ctyCode,cty Name English,cty Fullname English,Cty Abbreviation,Cty Comments,ISO2-digit Alpha,ISO3-digit Alpha,Start Valid Year,End Valid Year
0,0,World,World,World,NaN,WL,WLD,1962,2061
1,4,Afghanistan,Afghanistan,Afghanistan,NaN,AF,AFG,1962,2061
2,8,Albania,Albania,Albania,NaN,AL,ALB,1962,2061
3,10,Antarctica,Antarctica,Antarctica,NaN,NaN,ATA,1962,2061
4,12,Algeria,Algeria,Algeria,NaN,DZ,DZA,1962,2061
...,...,...,...,...,...,...,...,...,...
288,887,Yemen,Yemen,Yemen,NaN,YE,YEM,1991,2061
289,890,Fmr Yugoslavia,Former Yugoslavia,Fmr Yugoslavia,In 1992 including TFYR of Macedonia,YU,YUG,1962,1991
290,891,Serbia and Montenegro,Serbia and Montenegro,Serbia and Montenegro,NaN,CS,SCG,1992,2005
291,894,Zambia,Zambia,Zambia,NaN,ZM,ZMB,1965,2061
292,899,"Areas, nes","Areas, not elsewhere specified","Areas, nes",NaN,NaN,NaN,1962,2061

In [45]:
print(country_list['ISO3-digit Alpha'])
print(country_list.ctyCode)

0      WLD
1      AFG
2      ALB
3      ATA
4      DZA
      ...
288    YEM
289    YUG
290    SCG
291    ZMB
292    NaN
Name: ISO3-digit Alpha, Length: 293, dtype: object
0        0
1        4
2        8
3       10
4       12
      ...
288    887
289    890
290    891
291    894
292    899
Name: ctyCode, Length: 293, dtype: int64

In [1]:
import numpy as np
import pandas as pd
# cargo clase y funciones creadas por Eoin O'Keeffe para descargar datos de UNComtrade
import getTradeDataFromComtrade

In [2]:
comapi = getTradeDataFromComtrade.ComtradeApi()
# prueba con un pais y un producto
df = comapi.getComtradeData(comcodes=["1206"], reporter=['32'], partner=['0'], years=[2019], freq='A', rg=['1'], fmt='json', rowmax=50000)

C:\Programas\miniconda3\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'comtrade.un.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

In [3]:
df.cmdCode

0    1206
Name: cmdCode, dtype: object

In [4]:
df

,pfCode,yr,period,periodDesc,aggrLevel,IsLeaf,rgCode,rgDesc,rtCode,rtTitle,...,qtAltCode,qtAltDesc,TradeQuantity,AltQuantity,NetWeight,GrossWeight,TradeValue,CIFValue,FOBValue,estCode
0,H5,2019,2019,2019,4,0,1,Import,32,Argentina,...,None,,572579,None,572579,None,2077726,None,None,0

In [17]:
## pruebo con 2 paÃ­ses y 2 productos
df2 = comapi.getComtradeData(comcodes=['1206',"1005"], reporter=['32','28'], partner=['0'], years=[2017], freq='A', rg=['1'], fmt='json', rowmax=50000)

C:\Programas\miniconda3\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'comtrade.un.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

In [18]:
df2

,pfCode,yr,period,periodDesc,aggrLevel,IsLeaf,rgCode,rgDesc,rtCode,rtTitle,...,qtAltCode,qtAltDesc,TradeQuantity,AltQuantity,NetWeight,GrossWeight,TradeValue,CIFValue,FOBValue,estCode
0,H4,2017,2017,2017,4,0,1,Import,32,Argentina,...,None,,11115666,None,11115666,None,29400199,None,None,0
1,H4,2017,2017,2017,4,0,1,Import,32,Argentina,...,None,,360233,None,360233,None,2134731,None,None,0
2,H3,2017,2017,2017,4,0,1,Import,28,Antigua and Barbuda,...,None,,53189,None,53189,None,101326,None,None,0
3,H3,2017,2017,2017,4,0,1,Import,28,Antigua and Barbuda,...,None,,3636,None,3636,None,11217,None,None,0

In [19]:
# pruebo con un loop para consutlar distintos aÃ±os
year = ['2017','2018','2019']
appended_data = []
for y in range(0,3):
    data_prod = comapi.getComtradeData(comcodes=['1206', '0409', '1005'], reporter=['32'], partner=['0'], years=[year[y]], freq='A', rg=['1'], fmt='json', rowmax=50000)
    # store DataFrame in list
    appended_data.append(data_prod)
# see pd.concat documentation for more info
appended_data = pd.concat(appended_data)

C:\Programas\miniconda3\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'comtrade.un.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Programas\miniconda3\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'comtrade.un.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Programas\miniconda3\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'comtrade.un.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

In [21]:
# ok funciona
appended_data

,pfCode,yr,period,periodDesc,aggrLevel,IsLeaf,rgCode,rgDesc,rtCode,rtTitle,...,qtAltCode,qtAltDesc,TradeQuantity,AltQuantity,NetWeight,GrossWeight,TradeValue,CIFValue,FOBValue,estCode
0,H4,2017,2017,2017,4,0,1,Import,32,Argentina,...,None,,11115666,None,11115666,None,29400199,None,None,0
1,H4,2017,2017,2017,4,0,1,Import,32,Argentina,...,None,,360233,None,360233,None,2134731,None,None,0
0,H5,2018,2018,2018,4,0,1,Import,32,Argentina,...,None,,6741541,None,6741541,None,29827498,None,None,6
1,H5,2018,2018,2018,4,0,1,Import,32,Argentina,...,None,,219566,None,219566,None,1684597,None,None,6
0,H5,2019,2019,2019,4,0,1,Import,32,Argentina,...,None,,5140768,None,5140768,None,19504599,None,None,0
1,H5,2019,2019,2019,4,0,1,Import,32,Argentina,...,None,,572579,None,572579,None,2077726,None,None,0

In [47]:
# descargo lista completa de paÃ­ses
country_list = pd.read_csv(r'UN Comtrade Country List.csv')
country_list

,ctyCode,cty Name English,cty Fullname English,Cty Abbreviation,Cty Comments,ISO2-digit Alpha,ISO3-digit Alpha,Start Valid Year,End Valid Year
0,0,World,World,World,NaN,WL,WLD,1962,2061
1,4,Afghanistan,Afghanistan,Afghanistan,NaN,AF,AFG,1962,2061
2,8,Albania,Albania,Albania,NaN,AL,ALB,1962,2061
3,10,Antarctica,Antarctica,Antarctica,NaN,NaN,ATA,1962,2061
4,12,Algeria,Algeria,Algeria,NaN,DZ,DZA,1962,2061
...,...,...,...,...,...,...,...,...,...
288,887,Yemen,Yemen,Yemen,NaN,YE,YEM,1991,2061
289,890,Fmr Yugoslavia,Former Yugoslavia,Fmr Yugoslavia,In 1992 including TFYR of Macedonia,YU,YUG,1962,1991
290,891,Serbia and Montenegro,Serbia and Montenegro,Serbia and Montenegro,NaN,CS,SCG,1992,2005
291,894,Zambia,Zambia,Zambia,NaN,ZM,ZMB,1965,2061
292,899,"Areas, nes","Areas, not elsewhere specified","Areas, nes",NaN,NaN,NaN,1962,2061

In [45]:
# armo lista de paÃ­ses para hacer la consulta en Comtrade
len(country_list.ctyCode)
countries = country_list.ctyCode
print(type(countries.to_list()))
countries_string = [str(x) for x in  countries.to_list()]
print(countries_string)

<class 'list'>
['0', '4', '8', '10', '12', '16', '20', '24', '28', '31', '32', '36', '40', '44', '48', '50', '51', '52', '56', '58', '60', '64', '68', '70', '72', '74', '76', '80', '84', '86', '90', '92', '96', '97', '100', '104', '108', '112', '116', '120', '124', '129', '132', '136', '140', '144', '148', '152', '156', '162', '166', '170', '174', '175', '178', '180', '184', '188', '191', '192', '196', '200', '203', '204', '208', '212', '214', '218', '221', '222', '226', '230', '231', '232', '233', '234', '238', '239', '242', '246', '251', '254', '258', '260', '262', '266', '268', '270', '275', '276', '278', '280', '288', '290', '292', '296', '300', '304', '308', '312', '316', '320', '324', '328', '332', '334', '336', '340', '344', '348', '352', '356', '360', '364', '368', '372', '376', '381', '384', '388', '392', '398', '400', '404', '408', '410', '414', '417', '418', '422', '426', '428', '430', '434', '440', '442', '446', '450', '454', '457', '458', '459', '461', '462', '466', '470', '471', '472', '473', '474', '478', '480', '484', '490', '492', '496', '498', '499', '500', '504', '508', '512', '516', '520', '524', '527', '528', '530', '531', '532', '533', '534', '535', '536', '540', '548', '554', '558', '562', '566', '568', '570', '574', '577', '579', '580', '581', '582', '583', '584', '585', '586', '588', '590', '591', '592', '598', '600', '604', '608', '612', '616', '620', '624', '626', '634', '636', '637', '638', '642', '643', '646', '647', '654', '658', '659', '660', '662', '666', '670', '674', '678', '682', '686', '688', '690', '694', '697', '698', '699', '702', '703', '704', '705', '706', '710', '711', '716', '717', '720', '724', '728', '729', '732', '736', '740', '748', '752', '757', '760', '762', '764', '768', '772', '776', '780', '784', '788', '792', '795', '796', '798', '800', '804', '807', '810', '818', '826', '834', '835', '836', '837', '838', '839', '841', '842', '849', '850', '854', '858', '860', '862', '866', '868', '876', '879', '882', '886', '887', '890', '891', '894', '899']

In [52]:
# descargo lista completa de bienes
lista_bienes = pd.read_excel(r'UN Comtrade Commodity Classifications.xlsx')
lista_bienes

,Classification,Code,Description,Code Parent,Level,isLeaf
0,BE,1,Food and beverages,TOTAL,1,0
1,BE,11,"Food and beverages, primary",1,2,0
2,BE,111,"Food and beverages, primary, mainly for industry",11,3,1
3,BE,112,"Food and beverages, primary, mainly for househ...",11,3,1
4,BE,12,"Food and beverages, processed",1,2,0
...,...,...,...,...,...,...
51755,S4,9710,"Gold, non-monetary (excluding gold ores and co...",971,4,0
51756,S4,97101,"Gold (including gold plated with platinum), no...",9710,5,1
51757,S4,97102,"Base metals/silver, clad with gold, semi-manuf...",9710,5,1
51758,S4,97103,Waste & scrap of gold & ash containing preciou...,9710,5,1
51759,S4,TOTAL,All Commodities,NaN,0,0

In [58]:
# selecciono codigo de bienes a 4 dÃ­gitos del sistema armonizado 
# H1 corresponde a la nomenclatura de 1996 para poder comparar con aÃ±os posteriores
# idea comparar un promedio de aÃ±os para los Ãºltimos 20 aÃ±os: 1997-99, 2007-09 y 2017-19 
lista_bienes[lista_bienes['Code'].map(len) == 4].Classification.unique()

array(['H0', 'H1', 'H2', 'H3', 'H4', 'H5', 'S1', 'S2', 'S3', 'S4'],
      dtype=object)

In [62]:
# selecciono 4 digitos y H1
bienes_4dig = lista_bienes[(lista_bienes['Code'].map(len) == 4) & (lista_bienes['Classification'] == 'H1')]
bienes_4dig

,Classification,Code,Description,Code Parent,Level,isLeaf
6412,H1,0101,"Horses, asses, mules and hinnies; live",01,4,0
6416,H1,0102,Bovine animals; live,01,4,0
6419,H1,0103,Swine; live,01,4,0
6423,H1,0104,Sheep and goats; live,01,4,0
6426,H1,0105,"Poultry; live, fowls of the species gallus dom...",01,4,0
...,...,...,...,...,...,...
12872,H1,9703,"Sculptures and statuary; original, in any mate...",97,4,0
12874,H1,9704,"Stamps, postage or revenue; stamp-postmarks, f...",97,4,0
12876,H1,9705,Collections and collectors' pieces; of zoologi...,97,4,0
12878,H1,9706,Antiques; of an age exceeding one hundred years,97,4,0
12881,H1,9999,Commodities not specified according to kind,99,4,0

In [73]:
# armo lista para hacer consulta en comtrade
cod_bs_4dig = bienes_4dig.Code.to_list()
len(cod_bs_4dig)

1242

In [87]:
type(cod_bs_4dig)
cod_bs_4dig[1239:]

['9705', '9706', '9999']

In [90]:
# pruebo con una consulta para todos los productos con un paÃ­s y un aÃ±o
comapi.getComtradeData(comcodes=cod_bs_4dig[1239:], reporter=['32'], partner=['0'], years=['2019'], freq='A', rg=['1'], fmt='json', rowmax=50000)

C:\Programas\miniconda3\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'comtrade.un.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

,pfCode,yr,period,periodDesc,aggrLevel,IsLeaf,rgCode,rgDesc,rtCode,rtTitle,...,qtAltCode,qtAltDesc,TradeQuantity,AltQuantity,NetWeight,GrossWeight,TradeValue,CIFValue,FOBValue,estCode
0,H5,2019,2019,2019,4,0,1,Import,32,Argentina,...,None,,0,None,0,None,583517764,None,None,0
1,H5,2019,2019,2019,4,0,1,Import,32,Argentina,...,None,,2910,None,2910,None,3998204,None,None,0
2,H5,2019,2019,2019,4,0,1,Import,32,Argentina,...,None,,3956,None,3956,None,183748,None,None,0

In [67]:
# Armo consulta para iterar sobre 3 aÃ±os
# consulto todos los bienes a 4 dÃ­gitos (H1)
# reporter = todos los paÃ­ses
# partner = Mundo
# trade flow = imports 
year = ['2017','2018','2019']
appended_data = []
for y in range(0,3):
        data_prod = comapi.getComtradeData(comcodes=cod_bs_4dig, reporter=countries_string, partner=['0'], years=[year[y]], freq='A', rg=['1'], fmt='json', rowmax=50000)
        # store DataFrame in list
        appended_data.append(data_prod)
        # see pd.concat documentation for more info
appended_data = pd.concat(appended_data)

C:\Programas\miniconda3\lib\site-packages\urllib3\connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'comtrade.un.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
WARNING:root:No json object to be parsed
WARNING:root:Trying running the string below in your browser -is there an error?
WARNING:root:return string: <Response [404]>
WARNING:root:https://comtrade.un.org/api/get?type=C&freq=A&px=HS&ps=2017&r=0%2C4%2C8%2C10%2C12%2C16%2C20%2C24%2C28%2C31%2C32%2C36%2C40%2C44%2C48%2C50%2C51%2C52%2C56%2C58%2C60%2C64%2C68%2C70%2C72%2C74%2C76%2C80%2C84%2C86%2C90%2C92%2C96%2C97%2C100%2C104%2C108%2C112%2C116%2C120%2C124%2C129%2C132%2C136%2C140%2C144%2C148%2C152%2C156%2C162%2C166%2C170%2C174%2C175%2C178%2C180%2C184%2C188%2C191%2C192%2C196%2C200%2C203%2C204%2C208%2C212%2C214%2C218%2C221%2C222%2C226%2C230%2C231%2C232%2C233%2C234%2C238%2C239%2C242%2C246%2C251%2C254%2C258%2C260%2C262%2C266%2C268%2C270%2C275%2C276%2C278%2C280%2C288%2C290%2C292%2C296%2C300%2C304%2C308%2C312%2C316%2C320%2C324%2C328%2C332%2C334%2C336%2C340%2C344%2C348%2C352%2C356%2C360%2C364%2C368%2C372%2C376%2C381%2C384%2C388%2C392%2C398%2C400%2C404%2C408%2C410%2C414%2C417%2C418%2C422%2C426%2C428%2C430%2C434%2C440%2C442%2C446%2C450%2C454%2C457%2C458%2C459%2C461%2C462%2C466%2C470%2C471%2C472%2C473%2C474%2C478%2C480%2C484%2C490%2C492%2C496%2C498%2C499%2C500%2C504%2C508%2C512%2C516%2C520%2C524%2C527%2C528%2C530%2C531%2C532%2C533%2C534%2C535%2C536%2C540%2C548%2C554%2C558%2C562%2C566%2C568%2C570%2C574%2C577%2C579%2C580%2C581%2C582%2C583%2C584%2C585%2C586%2C588%2C590%2C591%2C592%2C598%2C600%2C604%2C608%2C612%2C616%2C620%2C624%2C626%2C634%2C636%2C637%2C638%2C642%2C643%2C646%2C647%2C654%2C658%2C659%2C660%2C662%2C666%2C670%2C674%2C678%2C682%2C686%2C688%2C690%2C694%2C697%2C698%2C699%2C702%2C703%2C704%2C705%2C706%2C710%2C711%2C716%2C717%2C720%2C724%2C728%2C729%2C732%2C736%2C740%2C748%2C752%2C757%2C760%2C762%2C764%2C768%2C772%2C776%2C780%2C784%2C788%2C792%2C795%2C796%2C798%2C800%2C804%2C807%2C810%2C818%2C826%2C834%2C835%2C836%2C837%2C838%2C839%2C841%2C842%2C849%2C850%2C854%2C858%2C860%2C862%2C866%2C868%2C876%2C879%2C882%2C886%2C887%2C890%2C891%2C894%2C899&p=0&rg=1&cc=101%2C102%2C103%2C104%2C105%2C106%2C201%2C202%2C203%2C204%2C205%2C206%2C207%2C208%2C209%2C210%2C301%2C302%2C303%2C304%2C305%2C306%2C307%2C401%2C402%2C403%2C404%2C405%2C406%2C407%2C408%2C409%2C410%2C501%2C502%2C503%2C504%2C505%2C506%2C507%2C508%2C509%2C510%2C511%2C601%2C602%2C603%2C604%2C701%2C702%2C703%2C704%2C705%2C706%2C707%2C708%2C709%2C710%2C711%2C712%2C713%2C714%2C801%2C802%2C803%2C804%2C805%2C806%2C807%2C808%2C809%2C810%2C811%2C812%2C813%2C814%2C901%2C902%2C903%2C904%2C905%2C906%2C907%2C908%2C909%2C910%2C1001%2C1002%2C1003%2C1004%2C1005%2C1006%2C1007%2C1008%2C1101%2C1102%2C1103%2C1104%2C1105%2C1106%2C1107%2C1108%2C1109%2C1201%2C1202%2C1203%2C1204%2C1205%2C1206%2C1207%2C1208%2C1209%2C1210%2C1211%2C1212%2C1213%2C1214%2C1301%2C1302%2C1401%2C1402%2C1403%2C1404%2C1501%2C1502%2C1503%2C1504%2C1505%2C1506%2C1507%2C1508%2C1509%2C1510%2C1511%2C1512%2C1513%2C1514%2C1515%2C1516%2C1517%2C1518%2C1520%2C1521%2C1522%2C1601%2C1602%2C1603%2C1604%2C1605%2C1701%2C1702%2C1703%2C1704%2C1801%2C1802%2C1803%2C1804%2C1805%2C1806%2C1901%2C1902%2C1903%2C1904%2C1905%2C2001%2C2002%2C2003%2C2004%2C2005%2C2006%2C2007%2C2008%2C2009%2C2101%2C2102%2C2103%2C2104%2C2105%2C2106%2C2201%2C2202%2C2203%2C2204%2C2205%2C2206%2C2207%2C2208%2C2209%2C2301%2C2302%2C2303%2C2304%2C2305%2C2306%2C2307%2C2308%2C2309%2C2401%2C2402%2C2403%2C2501%2C2502%2C2503%2C2504%2C2505%2C2506%2C2507%2C2508%2C2509%2C2510%2C2511%2C2512%2C2513%2C2514%2C2515%2C2516%2C2517%2C2518%2C2519%2C2520%2C2521%2C2522%2C2523%2C2524%2C2525%2C2526%2C2527%2C2528%2C2529%2C2530%2C2601%2C2602%2C2603%2C2604%2C2605%2C2606%2C2607%2C2608%2C2609%2C2610%2C2611%2C2612%2C2613%2C2614%2C2615%2C2616%2C2617%2C2618%2C2619%2C2620%2C2621%2C2701%2C2702%2C2703%2C2704%2C2705%2C2706%2C2707%2C2708%2C2709%2C2710%2C2711%2C2712%2C2713%2C2714%2C2715%2C2716%2C2801%2C2802%2C2803%2C2804%2C2805%2C2806%2C2807%2C2808%2C2809%2C2810%2C2811%2C2812%2C2813%2C2814%2C2815%2C2816%2C2817%2C2818%2C2819%2C2820%2C2821%2C2822%2C2823%2C2824%2C2825%2C2826%2C2827%2C2828%2C2829%2C2830%2C2831%2C2832%2C2833%2C2834%2C2835%2C2836%2C2837%2C2838%2C2839%2C2840%2C2841%2C2842%2C2843%2C2844%2C2845%2C2846%2C2847%2C2848%2C2849%2C2850%2C2851%2C2901%2C2902%2C2903%2C2904%2C2905%2C2906%2C2907%2C2908%2C2909%2C2910%2C2911%2C2912%2C2913%2C2914%2C2915%2C2916%2C2917%2C2918%2C2919%2C2920%2C2921%2C2922%2C2923%2C2924%2C2925%2C2926%2C2927%2C2928%2C2929%2C2930%2C2931%2C2932%2C2933%2C2934%2C2935%2C2936%2C2937%2C2938%2C2939%2C2940%2C2941%2C2942%2C3001%2C3002%2C3003%2C3004%2C3005%2C3006%2C3101%2C3102%2C3103%2C3104%2C3105%2C3201%2C3202%2C3203%2C3204%2C3205%2C3206%2C3207%2C3208%2C3209%2C3210%2C3211%2C3212%2C3213%2C3214%2C3215%2C3301%2C3302%2C3303%2C3304%2C3305%2C3306%2C3307%2C3401%2C3402%2C3403%2C3404%2C3405%2C3406%2C3407%2C3501%2C3502%2C3503%2C3504%2C3505%2C3506%2C3507%2C3601%2C3602%2C3603%2C3604%2C3605%2C3606%2C3701%2C3702%2C3703%2C3704%2C3705%2C3706%2C3707%2C3801%2C3802%2C3803%2C3804%2C3805%2C3806%2C3807%2C3808%2C3809%2C3810%2C3811%2C3812%2C3813%2C3814%2C3815%2C3816%2C3817%2C3818%2C3819%2C3820%2C3821%2C3822%2C3823%2C3824%2C3901%2C3902%2C3903%2C3904%2C3905%2C3906%2C3907%2C3908%2C3909%2C3910%2C3911%2C3912%2C3913%2C3914%2C3915%2C3916%2C3917%2C3918%2C3919%2C3920%2C3921%2C3922%2C3923%2C3924%2C3925%2C3926%2C4001%2C4002%2C4003%2C4004%2C4005%2C4006%2C4007%2C4008%2C4009%2C4010%2C4011%2C4012%2C4013%2C4014%2C4015%2C4016%2C4017%2C4101%2C4102%2C4103%2C4104%2C4105%2C4106%2C4107%2C4108%2C4109%2C4110%2C4111%2C4201%2C4202%2C4203%2C4204%2C4205%2C4206%2C4301%2C4302%2C4303%2C4304%2C4401%2C4402%2C4403%2C4404%2C4405%2C4406%2C4407%2C4408%2C4409%2C4410%2C4411%2C4412%2C4413%2C4414%2C4415%2C4416%2C4417%2C4418%2C4419%2C4420%2C4421%2C4501%2C4502%2C4503%2C4504%2C4601%2C4602%2C4701%2C4702%2C4703%2C4704%2C4705%2C4706%2C4707%2C4801%2C4802%2C4803%2C4804%2C4805%2C4806%2C4807%2C4808%2C4809%2C4810%2C4811%2C4812%2C4813%2C4814%2C4815%2C4816%2C4817%2C4818%2C4819%2C4820%2C4821%2C4822%2C4823%2C4901%2C4902%2C4903%2C4904%2C4905%2C4906%2C4907%2C4908%2C4909%2C4910%2C4911%2C5001%2C5002%2C5003%2C5004%2C5005%2C5006%2C5007%2C5101%2C5102%2C5103%2C5104%2C5105%2C5106%2C5107%2C5108%2C5109%2C5110%2C5111%2C5112%2C5113%2C5201%2C5202%2C5203%2C5204%2C5205%2C5206%2C5207%2C5208%2C5209%2C5210%2C5211%2C5212%2C5301%2C5302%2C5303%2C5304%2C5305%2C5306%2C5307%2C5308%2C5309%2C5310%2C5311%2C5401%2C5402%2C5403%2C5404%2C5405%2C5406%2C5407%2C5408%2C5501%2C5502%2C5503%2C5504%2C5505%2C5506%2C5507%2C5508%2C5509%2C5510%2C5511%2C5512%2C5513%2C5514%2C5515%2C5516%2C5601%2C5602%2C5603%2C5604%2C5605%2C5606%2C5607%2C5608%2C5609%2C5701%2C5702%2C5703%2C5704%2C5705%2C5801%2C5802%2C5803%2C5804%2C5805%2C5806%2C5807%2C5808%2C5809%2C5810%2C5811%2C5901%2C5902%2C5903%2C5904%2C5905%2C5906%2C5907%2C5908%2C5909%2C5910%2C5911%2C6001%2C6002%2C6101%2C6102%2C6103%2C6104%2C6105%2C6106%2C6107%2C6108%2C6109%2C6110%2C6111%2C6112%2C6113%2C6114%2C6115%2C6116%2C6117%2C6201%2C6202%2C6203%2C6204%2C6205%2C6206%2C6207%2C6208%2C6209%2C6210%2C6211%2C6212%2C6213%2C6214%2C6215%2C6216%2C6217%2C6301%2C6302%2C6303%2C6304%2C6305%2C6306%2C6307%2C6308%2C6309%2C6310%2C6401%2C6402%2C6403%2C6404%2C6405%2C6406%2C6501%2C6502%2C6503%2C6504%2C6505%2C6506%2C6507%2C6601%2C6602%2C6603%2C6701%2C6702%2C6703%2C6704%2C6801%2C6802%2C6803%2C6804%2C6805%2C6806%2C6807%2C6808%2C6809%2C6810%2C6811%2C6812%2C6813%2C6814%2C6815%2C6901%2C6902%2C6903%2C6904%2C6905%2C6906%2C6907%2C6908%2C6909%2C6910%2C6911%2C6912%2C6913%2C6914%2C7001%2C7002%2C7003%2C7004%2C7005%2C7006%2C7007%2C7008%2C7009%2C7010%2C7011%2C7012%2C7013%2C7014%2C7015%2C7016%2C7017%2C7018%2C7019%2C7020%2C7101%2C7102%2C7103%2C7104%2C7105%2C7106%2C7107%2C7108%2C7109%2C7110%2C7111%2C7112%2C7113%2C7114%2C7115%2C7116%2C7117%2C7118%2C7201%2C7202%2C7203%2C7204%2C7205%2C7206%2C7207%2C7208%2C7209%2C7210%2C7211%2C7212%2C7213%2C7214%2C7215%2C7216%2C7217%2C7218%2C7219%2C7220%2C7221%2C7222%2C7223%2C7224%2C7225%2C7226%2C7227%2C7228%2C7229%2C7301%2C7302%2C7303%2C7304%2C7305%2C7306%2C7307%2C7308%2C7309%2C7310%2C7311%2C7312%2C7313%2C7314%2C7315%2C7316%2C7317%2C7318%2C7319%2C7320%2C7321%2C7322%2C7323%2C7324%2C7325%2C7326%2C7401%2C7402%2C7403%2C7404%2C7405%2C7406%2C7407%2C7408%2C7409%2C7410%2C7411%2C7412%2C7413%2C7414%2C7415%2C7416%2C7417%2C7418%2C7419%2C7501%2C7502%2C7503%2C7504%2C7505%2C7506%2C7507%2C7508%2C7601%2C7602%2C7603%2C7604%2C7605%2C7606%2C7607%2C7608%2C7609%2C7610%2C7611%2C7612%2C7613%2C7614%2C7615%2C7616%2C7801%2C7802%2C7803%2C7804%2C7805%2C7806%2C7901%2C7902%2C7903%2C7904%2C7905%2C7906%2C7907%2C8001%2C8002%2C8003%2C8004%2C8005%2C8006%2C8007%2C8101%2C8102%2C8103%2C8104%2C8105%2C8106%2C8107%2C8108%2C8109%2C8110%2C8111%2C8112%2C8113%2C8201%2C8202%2C8203%2C8204%2C8205%2C8206%2C8207%2C8208%2C8209%2C8210%2C8211%2C8212%2C8213%2C8214%2C8215%2C8301%2C8302%2C8303%2C8304%2C8305%2C8306%2C8307%2C8308%2C8309%2C8310%2C8311%2C8401%2C8402%2C8403%2C8404%2C8405%2C8406%2C8407%2C8408%2C8409%2C8410%2C8411%2C8412%2C8413%2C8414%2C8415%2C8416%2C8417%2C8418%2C8419%2C8420%2C8421%2C8422%2C8423%2C8424%2C8425%2C8426%2C8427%2C8428%2C8429%2C8430%2C8431%2C8432%2C8433%2C8434%2C8435%2C8436%2C8437%2C8438%2C8439%2C8440%2C8441%2C8442%2C8443%2C8444%2C8445%2C8446%2C8447%2C8448%2C8449%2C8450%2C8451%2C8452%2C8453%2C8454%2C8455%2C8456%2C8457%2C8458%2C8459%2C8460%2C8461%2C8462%2C8463%2C8464%2C8465%2C8466%2C8467%2C8468%2C8469%2C8470%2C8471%2C8472%2C8473%2C8474%2C8475%2C8476%2C8477%2C8478%2C8479%2C8480%2C8481%2C8482%2C8483%2C8484%2C8485%2C8501%2C8502%2C8503%2C8504%2C8505%2C8506%2C8507%2C8508%2C8509%2C8510%2C8511%2C8512%2C8513%2C8514%2C8515%2C8516%2C8517%2C8518%2C8519%2C8520%2C8521%2C8522%2C8523%2C8524%2C8525%2C8526%2C8527%2C8528%2C8529%2C8530%2C8531%2C8532%2C8533%2C8534%2C8535%2C8536%2C8537%2C8538%2C8539%2C8540%2C8541%2C8542%2C8543%2C8544%2C8545%2C8546%2C8547%2C8548%2C8601%2C8602%2C8603%2C8604%2C8605%2C8606%2C8607%2C8608%2C8609%2C8701%2C8702%2C8703%2C8704%2C8705%2C8706%2C8707%2C8708%2C8709%2C8710%2C8711%2C8712%2C8713%2C8714%2C8715%2C8716%2C8801%2C8802%2C8803%2C8804%2C8805%2C8901%2C8902%2C8903%2C8904%2C8905%2C8906%2C8907%2C8908%2C9001%2C9002%2C9003%2C9004%2C9005%2C9006%2C9007%2C9008%2C9009%2C9010%2C9011%2C9012%2C9013%2C9014%2C9015%2C9016%2C9017%2C9018%2C9019%2C9020%2C9021%2C9022%2C9023%2C9024%2C9025%2C9026%2C9027%2C9028%2C9029%2C9030%2C9031%2C9032%2C9033%2C9101%2C9102%2C9103%2C9104%2C9105%2C9106%2C9107%2C9108%2C9109%2C9110%2C9111%2C9112%2C9113%2C9114%2C9201%2C9202%2C9203%2C9204%2C9205%2C9206%2C9207%2C9208%2C9209%2C9301%2C9302%2C9303%2C9304%2C9305%2C9306%2C9307%2C9401%2C9402%2C9403%2C9404%2C9405%2C9406%2C9501%2C9502%2C9503%2C9504%2C9505%2C9506%2C9507%2C9508%2C9601%2C9602%2C9603%2C9604%2C9605%2C9606%2C9607%2C9608%2C9609%2C9610%2C9611%2C9612%2C9613%2C9614%2C9615%2C9616%2C9617%2C9618%2C9701%2C9702%2C9703%2C9704%2C9705%2C9706%2C9999&fmt=json&max=50000&head=M

WARNING:root:<class 'json.decoder.JSONDecodeError'> Expecting value: line 1 column 1 (char 0)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [94]:
import requests
url='https://comtrade.un.org/api/get?max=100&type=C&freq=A&px=HS&ps=2019&r=all&p=World&rg=all&cc=9999'
un_data=requests.get(url)
print(un_data.content)

b'{"validation":{"status":{"name":"Invalid parameter","value":5004,"category":0,"description":"the selected query does not accept the passed option.","helpUrl":"For more reference visit http://comtrade.un.org/data/dev/portal/"},"message":"Invalid argument format: \'World\', integers and keywords \'ALL\' only acceptable values","count":{"value":0,"started":"0001-01-01T00:00:00","finished":"0001-01-01T00:00:00","durationSeconds":0.0},"datasetTimer":null},"dataset":[]}'